### ISSUE TITLE
No need to use the word "swagger" anywhere

### ISSUE THREAD

**Issue by philsturgeon** [fmvilas/openapi3-generator#5]
Hey, as this is an OpenAPI v3.0 tool, I wouldn't expect to see the word "swagger" showing up anywhere for anything. That is no longer the name of the specification, just the name of a few tools by SmartBear. 

Can we get rid of the word Swagger before this hits a v1.0?

**Comment by fmvilas** [comment]
Sure, Phil. I'll try to find some time this week to do it. Thanks!

**Comment by fmvilas** [comment]
So I had some time before I thought I would: https://github.com/fmvilas/openapi3-generator/commit/e2526e0a5cbd47e50dab035ed7ccabbc77146112.

It's already on npm. Let me know if you find something weird. Thanks @philsturgeon!
